feature(ruby): :rocket:
Widen/widen-sso-examples pull request #4
Opened 2019-09-09 22:26 UTC by dbeg

Adding another example app to generate Simple One-Way SSO requests, this time in Ruby (using Sinatra as the web framework).

Adding @kmancusi and @tabermike to review the rooby.

2019-09-10 13:24 UTC, tabermike submitted a review, later dismissed
Ahh, the simplicity of Sinatra...
Looks clean and simple.
👍

2019-09-10 13:35 UTC, kmancusi submitted a review, later dismissed
LGTM
The `app.rb` file is laid out understandably.
Naively, I have to go off of Taber's opinion more so in the fact he has a better understanding on:
1) look of this (and sinatra)
2) better future thinking vision

2019-09-10 16:41 UTC, forsethc requested changes

2019-09-11 15:49 UTC, forsethc approved these changes

2019-09-11 15:49 UTC, merged